Feat/api implementation
Web3-API/web3hub pull request #6
Opened 2021-03-19 05:31 UTC by cbrzn

2021-03-19 18:38 UTC, dOrgJelli reviewed
Looks like a great start @cbrzn! Left mainly code styling/structure related comments

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/app.ts
> +    // more info: https://tilomitra.com/how-do-nodejs-sessions-work/
I think tracking user sessions would be important for debugging. For example, if someone hits "publish" or something else that requires an API call, and gets an error back, we'd want that error to include a session ID so we can lookup the trace logs to figure out what went wrong.

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/app.ts
> +import express, { Application } from "express";
Nit: filename of a class should be capitalized (App.ts)

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/app.ts
> +import express, { Application } from "express";
Let's rename "Application" here to "ExpressApp" to be more explicit `{ Application as ExpressApp }`. Will help with readability.

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/app.ts
> +import express, { Application } from "express";
Or maybe even "ExpressServer" since `getServer` is defined below. Also renaming `this.app` to `this.server`

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/controllers/users.ts
> +const router = Router();
If we have the "App" class, shouldn't this be a class as well? Is there a case where we'd want to have multiple "App" instances, which use multiple Router instances? If not, we can make everything global instead of having class objects.

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/controllers/users.ts
> +export default router;
Nit: let's use named exports as we do in the core codebase. Default exports can cause problems with different node module resolution types (commonjs, etc).

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/models/User.ts
> +}
Is this necessary?

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/server.ts
> +app.listen();
Confused why we have both App and Server as primitives, why not just use Sever?

2021-03-19 18:38 UTC, dOrgJelli commented on packages/api/src/services/github/api.ts
> +interface OrganizationsDTO {
Does GitHub's API have TypeScript typings anywhere? Or maybe an API schema file (REST or GraphQL) we could generate this from?

2021-03-23 20:34 UTC, cbrzn commented on packages/api/src/app.ts
> +    // more info: https://tilomitra.com/how-do-nodejs-sessions-work/
Ok, then I will find a solution for production environment

2021-03-23 20:35 UTC, cbrzn commented on packages/api/src/controllers/users.ts
> +const router = Router();
Okok I will change `App` to be global instead of a class object

2021-03-23 20:36 UTC, cbrzn commented on packages/api/src/models/User.ts
> +}
The reason of this is that we want to access to the user object via the `Request session` of express, this means that we can do `request.session.OUR_CUSTOM_ATTRIBUTE` and typescript wont complain

2021-03-23 20:37 UTC, cbrzn commented on packages/api/src/server.ts
> +app.listen();
The reason is that, if we want to eventually test the API, we need the app object, not the server listening.

I can remove this, but I think that eventually creating a test suite for this would be awesome, let me know your thoughts please!

2021-03-23 20:41 UTC, cbrzn commented on packages/api/src/services/github/api.ts
> +interface OrganizationsDTO {
I didn't find one, that's why I came to this approach

2021-03-23 20:45 UTC, cbrzn commented on packages/api/src/server.ts
> +app.listen();
Also, I made this thinking that eventually we want to make this API serverless, and we would need to wrap the entire app object in a `serverless` object

2021-03-23 20:46 UTC, cbrzn commented on packages/api/src/app.ts
> +import express, { Application } from "express";
> Or maybe even "ExpressServer" since getServer is defined below. Also renaming this.app to this.server
This is related to: https://github.com/Web3-API/web3hub/pull/6#discussion_r599925144

And I think that we should not rename `this.app` to `this.server` because the app is the object with the routes and middlewares; and the server is the instance where we apply the `listen` in order to get the server up

2021-04-05 20:40 UTC, dOrgJelli commented on packages/api/src/server.ts
> +app.listen();
Ah okay great, makes sense!

2021-04-05 21:04 UTC, dOrgJelli requested changes

2021-04-05 21:04 UTC, dOrgJelli commented on packages/api/documentation/swagger/auth.json
> +              "address": {
I think we should rename this to `authId`, and change `addressType` to `authType`

2021-04-05 22:53 UTC, dOrgJelli requested changes

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/documentation/swagger/auth.json
> +          "description": "Unexpected error on APi",
Nit: "APi" -> "API"

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/app.ts
> +passport.use(GithubStrategy);
Could we add some comments for each middleware we're using? For those that aren't as familiar with these NPM packages (like myself), it'd really help understand what each one is doing.

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/models/User.ts
> +}
Can we please auto-generate these typescript types from the swagger JSON schemas? This way we can ensure changes to the schema are reflected in the codebase and propagate build errors when breaking changes are made.

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/controllers/apis.ts
> +SanitizeApis.getInstance();
This seems strange to kick-off the cronjob here. Why not export all cronjobs from the cronjob folder, and initiate them all when the server starts up?

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/models/Api.ts
> +      const apis = await connection.manyOrNone(
As the number of APIs available grows, we'll probably want to have pagination happening on the request level.

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/models/User.ts
> +  public static async findOrCreateByAddress({
Make "Address" ethereum specific, as we may support other types of addresses in the future

2021-04-05 22:53 UTC, dOrgJelli commented on packages/api/src/models/User.ts
> +    addressType = AddressesTypes.ETHEREUM,
addressType can be changed to authType?

2021-04-06 00:59 UTC, dOrgJelli commented
@cbrzn are you planning to add tests as well?

2021-04-06 02:05 UTC, evelynf reviewed
I have no context on this whatsoever so feel free to ignore any of my comments!!

2021-04-06 02:05 UTC, evelynf commented on packages/api/src/services/ens/index.ts
> +export const checkContentIsValid = async (
nit should this be in the index file or as separate validator files that will then be exported from index.ts?

2021-04-06 02:05 UTC, evelynf commented on packages/api/src/services/ens/index.ts
> +  const unvalidPointers = contents.filter(({ value }) => {
nit invalidPointers

2021-04-06 02:05 UTC, evelynf commented on packages/api/src/services/github/api.ts
> +      return null;
why not surface the error to the client?

2021-04-06 02:05 UTC, evelynf commented on packages/api/src/services/github/strategy.ts
> +interface GithubProfileDTO {
this is a super nit, but I'm still going to call it out, Api is written as so, but DTO is capitalized. I would say choose one pattern for acronyms and stick with it

2021-04-09 12:41 UTC, cbrzn commented on packages/api/docker-compose.yml
> +      - ./.env
Of course

2021-04-09 12:45 UTC, cbrzn commented on packages/api/documentation/swagger/models.json
> +      "location": {
Yup yup

2021-04-09 12:48 UTC, cbrzn commented on packages/api/src/app.ts
> +passport.use(GithubStrategy);
Yes, also, I plan to create an array of these middleware and create a function to implement them, something like this: https://github.com/dOrgTech/TxPayerService/blob/master/src/app.js#L23-L32 - I will add a comment to every element in the array

2021-04-09 12:52 UTC, cbrzn commented on packages/api/src/models/User.ts
> +}
We can, but I wouldn't spend time on this right now, since we are focusing on the implementation of the authentication, and the data might change - I create an issue for this: https://github.com/Web3-API/web3hub/issues/8

2021-04-09 12:53 UTC, cbrzn commented on packages/api/src/controllers/apis.ts
> +SanitizeApis.getInstance();
Makes sense, will do it!

2021-04-09 12:55 UTC, cbrzn commented on packages/api/src/models/User.ts
> +    addressType = AddressesTypes.ETHEREUM,
si!

2021-04-09 14:54 UTC, cbrzn commented on packages/api/documentation/swagger/models.json
> +      "address": {
Yes we can, the reason I made it that way it's because the data model has been thought to be extensible enough to support multiple -known- types of addresses (addresses -> user). The following tables has been implemented:

```sql
create table users (
  id bigserial not null,
  username varchar,
  github_id varchar,
  github_token varchar,
  primary key(id),
  UNIQUE(username),
  UNIQUE(github_id)
);
create table addresses_types (
  id bigserial not null,
  name varchar not null,
  primary key(id)
);
create table addresses (
  id bigserial not null,
  address varchar not null,
  fk_user_id bigint not null,
  fk_address_type_id bigint not null,
  UNIQUE(address),
  primary key(id),
  constraint fk_addresses_user foreign key (fk_user_id) references users(id),
  constraint fk_addresses_address_type foreign key (fk_address_type_id) references addresses_types(id)
);
```

This way, we can add as many types as we want, and they will be related to an address type - This will also allow us to manipulate the data in a more easy way, as we can filter addresses by type :-D

I'd say that we should stick with `address` because as Evelyn said, I feel that it is more extensible, lmk it this makes sense

On the business layer, i think it makes sense to create that `AuthId` interface and handle the session object with that structure

2021-04-09 14:55 UTC, cbrzn commented on packages/api/src/models/User.ts
> +  public static async findOrCreateByAddress({
related to: https://github.com/Web3-API/web3hub/pull/6#discussion_r607325598

2021-04-09 15:00 UTC, cbrzn commented on packages/api/src/controllers/apis.ts
> +  } catch (error) {
Indeed it does, but we want to handle the error in a "standard"  way so the UI always expect the same interface

2021-04-09 15:01 UTC, cbrzn commented on packages/api/src/controllers/helpers/index.ts
> +export * from "./validatePublishBody"
i thought about it too, but since there's just one so far (the validator from sign in endpoint has been removed) - i'd say to keep it this way and then if needed improve that

2021-04-09 15:02 UTC, cbrzn commented on packages/api/src/controllers/helpers/validatePublishBody.ts
> +import { NextFunction, Request, Response } from "express";
do you have any link to the code convention? would love to see it and apply it in the entire codebase :-D

2021-04-09 15:06 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +    const connection = await db.connect();
You're totally right! This should be improved :-D. Just for context: The reason we are doing it this way, is that we need to explicitly disconnect from the db on every request, because otherwise the connection would stay as idle...

The connect and disconnect **needs** to happen but I agree with you that it can be modularized

2021-04-09 15:07 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +        const api = await tx.one(
They are, we are using [Transactions from pg promise](https://github.com/Web3-API/web3hub/pull/6#discussion_r607392786) - If one fails there's a rollback :-D

2021-04-09 15:08 UTC, cbrzn commented on packages/api/src/services/db/create.sql
> +create table users (
It is, but I think it's not necessary right now as we the web3hub ui is interacting with the API in a REST way, or you have something else in mind?

2021-04-09 15:08 UTC, cbrzn commented on packages/api/src/services/db/create.sql
> +  UNIQUE(username),
Yah

2021-04-09 15:09 UTC, cbrzn commented on packages/api/src/controllers/users.ts
> +router.get("/user/orgs", isLoggedWithGithub, userOrganizations);
`IsLoggedWithGithub` is a middleware, or I am missing something?

2021-04-09 15:09 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +      console.log("Error on method: Api.deactivate() -> ", error.message);
That's an awesome idea, we don't have any plan for this but we should for sure

2021-04-09 15:12 UTC, cbrzn commented on packages/api/src/models/User.ts
> +      connection.done();
Makes sense, will apply that :-D

2021-04-09 15:17 UTC, cbrzn commented on packages/api/src/services/github/api.ts
> +      return null;
At first I thought that, if there's an error from github, the client shouldn't be aware of it... But now you are making me think 🤔  Maybe we should send the error to the client indeed

2021-04-09 15:18 UTC, cbrzn commented on packages/api/src/services/ens/index.ts
> +export const checkContentIsValid = async (
I think that it should be inside the `services/ens` folder since this is a validation specific from ENS (which interacts directly with their contracts)

2021-04-09 15:19 UTC, cbrzn commented on packages/api/src/controllers/apis.ts
> +  } catch (error) {
related to https://github.com/Web3-API/web3hub/pull/6#discussion_r610698060

2021-04-09 17:31 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +      const apis = await connection.manyOrNone(
Will create an issue for this

2021-04-09 17:32 UTC, cbrzn commented on packages/api/src/app.ts
> +app.use(morgan("combined"));
wdyt about this approach? https://github.com/Web3-API/web3hub/pull/6#discussion_r610598748

2021-04-09 17:54 UTC, cbrzn commented on packages/api/src/app.ts
> +import express, { Application as ExpressApp } from "express";
Sorry what you mean here?

2021-04-09 21:33 UTC, dOrgJelli commented on packages/api/documentation/swagger/models.json
> +      "address": {
address is still confusing to me, as we plan on not only integrating with pub/priv keypairs (addresses), but also web2 auths like github. Auth to me speaks to all of these use-cases, but totally up to you.

2021-04-10 17:16 UTC, evelynf commented on packages/api/src/services/ens/index.ts
> +export const checkContentIsValid = async (
just wondering if this should be moved into its own file and then imported into the index file

2021-04-10 17:16 UTC, evelynf commented on packages/api/src/services/github/api.ts
> +      return null;
I'm a proponent of being very transparent with errors since it makes debugging easier for us and the client

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/.env-example
> +RPC_NODE=
Nit: This is ambiguous since we'll be needing multiple node endpoints in the future. Should change to something like `ETH_RPC_NODE`

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +  "/api/actives": {
Nit: `actives` doesn't quite make sense, as well as having this under the `api` route doesn't make too much sense to me. What I've seen done in other APIs is there's both an `api` route which has API instance specific operations, and an `apis` route which has collection specific operations.

With this in mind, I'd suggest changing the route to `apis/active`

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +                "properties": {
Pagination query arguments + response properties are still missing here (just FYI)

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +                      "pointersUri": ["brazon.eth"],
Nit: `pointersUri` -> `pointerUris`

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +                      "pointersUri": ["brazon.eth"],
Also would suggest not using your last name in the example since this will show up in docs. Maybe `api.uniswap.eth` would be more fitting here.

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +      "summary": "Get all APIs",
Nit: Refer to Web3APIs as `Web3APIs` instead of `APIs`. This helps disambiguate things

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +          "example": { "Authorization": "token gho_TOKEN" },
Why is GitHub auth required for publishing a new API again?

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +          "example": { "Authorization": "token gho_TOKEN" },
Is this being used as the "root user ID" + auth in this case?

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +          "description": "API Metadata",
Nit: `Web3API Metadata`

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +      "description": "Store metadata ",
Nit: remove trailing space. Also move this up top underneath "summary"

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +  "/publish": {
Nit: Would nest this under the `apis/` route, since this is the `apis` API interface after all

2021-04-12 18:48 UTC, dOrgJelli commented on packages/api/documentation/swagger/apis.json
> +          "description": "Unexpected error on APi",
Nit: `APi` -> `API`

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/app.ts
> +    secret: "keyboard cat",
This should be set using ENV vars, and not publicly available. The secret is used to sign cookies within the session. If it's public, it could easily allow someone to tamper w/ session information. I'm not entirely sure of what the implications of all of this are, just going off of what I found here (ctrl+f "secret"):
https://stackoverflow.com/questions/5343131/what-is-the-sessions-secret-option
http://www.senchalabs.org/connect/session.html
https://nodesource.com/blog/nine-security-tips-to-keep-express-from-getting-pwned/

Here's a tutorial that uses an ENV value for the session secret: https://auth0.com/blog/create-a-simple-and-secure-node-express-app/

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/controllers/users.ts
> +router.get("/auth/github/callback/:code", authHandler);
Doesn't quite make sense to me to have these in the `users.ts` file, maybe create an `auth.ts` file

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/controllers/users.ts
> +router.get("/auth/github/callback/:code", authHandler);
Or nest the `auth` routes under `/user/`

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/models/Api.ts
> +export interface ApiData {
This interface doesn't match the swagger interface, is that a problem? Should really get auto-generated intefaces implemented sooner rather than later, will save a lot of time + debugging.

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/models/Api.ts
> +      console.log("Error on method: Api.deactivate() -> ", error.message);
For the client, we're using `OpenTelemetry` for logging. There's already a package setup for this, so maybe you could use it here as well! Here's the PR that adds this support: https://github.com/Web3-API/monorepo/pull/227

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/services/ens/index.ts
> +    ensAddress: getEnsAddress("3"),
As I'm sure you know, this is hardcoded to use chainID 3 (I think rinkeby). In the future we should be using the Web3API client directly here, and passing URIs so it can fetch them from any chain (this was implemented as part of the "Network Specific ENS Lookup" work that's merged here: https://github.com/Web3-API/monorepo/pull/228

The usage would look something like this:
```
const client = new Web3ApiClient()

const manifest = client.getManifest({ uri: "ens/rinkeby/api.foo.eth" })

...
```

2021-04-12 19:13 UTC, dOrgJelli commented on packages/api/src/services/ens/index.ts
> +    ensAddress: getEnsAddress("3"),
Correction: since we're validating the ContentID matches the ENS domain, we can use the ENS web3api to do this like so (psuedo code):
```
client.query({
  uri: "ens/ens.web3api.eth",
  query: `{
    getContentId(
      domain: "rinkeby/api.foo.eth"
    )
  }`
})
```

2021-04-12 19:13 UTC, dOrgJelli commented on packages/ui/src/components/tabs/PublishAPI.tsx
> +        const publishReq = await axios.post(
There must be a code generator out there to generate a JS SDK from a swagger schema. This way we don't have to "hard code" the arguments here, and hope they match the API schema.

2021-04-19 18:01 UTC, cbrzn commented on packages/api/src/app.ts
> +    secret: "keyboard cat",
Agreed! This was just for dev purposes, at this point it's worth to do it so I will :+1:

2021-04-20 13:41 UTC, merged

2021-04-20 13:43 UTC, jeffscottward commented
You can keep commit to this and we can merge that when its ready, I just wanted to get all my UI stuff in back to main

2021-04-20 18:19 UTC, cbrzn commented on packages/api/documentation/swagger/models.json
> +      "address": {
Will resolve this because it's going to be tackled in another PR https://github.com/Web3-API/web3hub/issues/11

2021-04-20 18:20 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +      const apis = await connection.manyOrNone(
https://github.com/Web3-API/web3hub/issues/9

2021-04-20 18:40 UTC, cbrzn commented on packages/api/src/controllers/apis.ts
> +  } catch (error) {
Let's tackle this here: https://github.com/Web3-API/web3hub/issues/13

2021-04-20 18:42 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +    const connection = await db.connect();
https://github.com/Web3-API/web3hub/issues/14

2021-04-20 18:44 UTC, cbrzn commented on packages/api/src/models/Api.ts
> +      console.log("Error on method: Api.deactivate() -> ", error.message);
https://github.com/Web3-API/web3hub/issues/15

2021-04-20 18:45 UTC, cbrzn commented on packages/api/src/services/github/api.ts
> +      return null;
Related to: https://github.com/Web3-API/web3hub/issues/13

2021-04-20 18:45 UTC, cbrzn commented on packages/api/documentation/swagger/apis.json
> +                "properties": {
https://github.com/Web3-API/web3hub/issues/9

2021-04-20 18:46 UTC, cbrzn commented on packages/api/documentation/swagger/apis.json
> +          "example": { "Authorization": "token gho_TOKEN" },
Will resolve this and let's discuss it in a call @dOrgJelli @jeffscottward

2021-04-20 18:54 UTC, cbrzn commented on packages/api/src/app.ts
> +    secret: "keyboard cat",
https://github.com/Web3-API/web3hub/pull/16

2021-04-20 19:08 UTC, cbrzn commented on packages/api/src/services/ens/index.ts
> +    ensAddress: getEnsAddress("3"),
https://github.com/Web3-API/web3hub/issues/17