Ens subdomains registration
Web3-API/web3hub pull request #7
Opened 2021-04-01 04:08 UTC by namesty

This PR includes necessary code for:

- Swap web3 for ethers and its wrapping class, taken from Web3API's monorepo

- ENS subdomain registration under "web3api.eth" domain
- ContentHash saving

- Domain owner resolution
- Domain contentHash resolution

Steps for testing:

- Connect wallet to ropsten
- Fill IPFS input
- Fill subdomain input
- Sign the 3 transaction prompts (register subdomain, set resolver, set content hash)

After a successful registration:

- Notice that when writing a new subdomain, the input field will show in red if the subdomain is already taken
- I didn't see where to output the content hash so I left that service unused for now but it's working, you can verify it with a simple invocation and console.log

2021-04-01 15:17 UTC, jeffscottward commented on packages/ui/src/components/SignInArea.tsx
> +    setShowConnectModal(true)
this is wrong - "Signin" is for Web2 stuff
we use the term "Connect" for web3 stuff.
There should be no connecting to web3 until you are on the publish page - hence the messaging on the modal that corresponds.
Please ask andrew if you have UX questions

2021-04-01 15:27 UTC, jeffscottward commented on packages/ui/src/utils/ethereum.ts
> +
We should not use ES6 classes anywhere. 
https://reactjs.org/docs/hooks-intro.html#classes-confuse-both-people-and-machines

Please convert.

2021-04-01 15:30 UTC, jeffscottward commented on packages/ui/src/utils/ethereum.ts
> +      // TODO: improve this
whats needed here?

2021-04-01 15:32 UTC, jeffscottward commented on packages/ui/src/components/SignInArea.tsx
> +    setShowConnectModal(true)
please return back to original setShowSignInModal and utilize signing in at the point of need on publish page when clicking Register ENS

2021-04-06 22:55 UTC, namesty commented on packages/ui/src/utils/ethereum.ts
> +
Ahh, but these are typescript classes, which do not contain the headaches of ES6 classes (well described in the article you linked).

The purpose of this class is to wrap the Ethers/Web3 class, so usage would be similar to how you would use the Web3 class or ethers class.

We could definitely refactor this into something else if you prefer though!

2021-04-06 23:24 UTC, namesty commented on packages/ui/src/utils/ethereum.ts
> +      // TODO: improve this
Was wondering what to return. If only the TX Hash or the whole TX object. I opted for the latter

2021-04-09 15:17 UTC, jeffscottward requested changes
Refactor eth wrap and drop a console log. Assuming it works, I'm just reviewing from my phone right now.

2021-04-09 15:17 UTC, jeffscottward commented on packages/ui/src/components/SignInArea.tsx
> +  console.log({ dapp })
Dump this

2021-04-09 15:17 UTC, jeffscottward commented on packages/ui/src/utils/ethereum.ts
> +
Oh I get the intent, that's fine, but it sticks out from the rest of the code base. 

There's overhead for having to remember the properties of this approach and how it maps back to actually what it represents in JS.

Function composition > syntax sugar.

Let's change it please.

2021-04-09 16:49 UTC, jeffscottward approved these changes

2021-04-09 16:49 UTC, merged